//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VPLoodsmanAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VPLoodsmanAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ACCESSLEVEL.
        /// </summary>
        internal static string AccessLevel {
            get {
                return ResourceManager.GetString("AccessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _MAIL.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _FILEDIR.
        /// </summary>
        internal static string FileDirectory {
            get {
                return ResourceManager.GetString("FileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _FULLNAME.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_LOCK.
        /// </summary>
        internal static string IDCheckOut {
            get {
                return ResourceManager.GetString("IDCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_LINK.
        /// </summary>
        internal static string IDLink {
            get {
                return ResourceManager.GetString("IDLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_LINKTYPE.
        /// </summary>
        internal static string IDLinkType {
            get {
                return ResourceManager.GetString("IDLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_MEASURE.
        /// </summary>
        internal static string IDMeasure {
            get {
                return ResourceManager.GetString("IDMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_STATE.
        /// </summary>
        internal static string IDState {
            get {
                return ResourceManager.GetString("IDState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_TYPE.
        /// </summary>
        internal static string IDType {
            get {
                return ResourceManager.GetString("IDType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ATTRTYPE.
        /// </summary>
        internal static string IDTypeAttribute {
            get {
                return ResourceManager.GetString("IDTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_UNIT.
        /// </summary>
        internal static string IDUnit {
            get {
                return ResourceManager.GetString("IDUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _ID_VERSION.
        /// </summary>
        internal static string IDVersion {
            get {
                return ResourceManager.GetString("IDVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _DOCUMENT.
        /// </summary>
        internal static string IsDocument {
            get {
                return ResourceManager.GetString("IsDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _SYSTEM.
        /// </summary>
        internal static string IsSystem {
            get {
                return ResourceManager.GetString("IsSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _PRODUCT.
        /// </summary>
        internal static string KeyAttribute {
            get {
                return ResourceManager.GetString("KeyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _LOCKED.
        /// </summary>
        internal static string LockLevel {
            get {
                return ResourceManager.GetString("LockLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _NAME.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _MEASURE.
        /// </summary>
        internal static string NameMeasure {
            get {
                return ResourceManager.GetString("NameMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _STATE.
        /// </summary>
        internal static string NameState {
            get {
                return ResourceManager.GetString("NameState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _TYPE.
        /// </summary>
        internal static string NameType {
            get {
                return ResourceManager.GetString("NameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _UNIT.
        /// </summary>
        internal static string NameUnit {
            get {
                return ResourceManager.GetString("NameUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _USERDIR.
        /// </summary>
        internal static string UserDirectory {
            get {
                return ResourceManager.GetString("UserDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _VALUE.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _VERSION.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
